version: '3'
services:
  db:
    image: 'postgres:latest'
    environment:
      POSTGRES_USER: User # The PostgreSQL user (useful to connect to the database)
      POSTGRES_PASSWORD: Citupia # The PostgreSQL password (useful to connect to the database)
      POSTGRES_DB: Citupia # The PostgreSQL default database (automatically created at first launch)
      POSTGRES_HOST_AUTH_METHOD: trust
    volumes:
      - /home/user/db:/var/lib/postgresql/data/
    restart: 'always'
    logging:
      driver: "json-file"
      options:
        max-size: "10k"
        max-file: "3"

  tpdjango:
    build:
        context: ./cit-backend
        dockerfile: Dockerfile
    ports:
        - "10000:8000"
    restart: 'always'
    logging:
      driver: "json-file"
      options:
        max-size: "10k"
        max-file: "3"
  tpvue:
    build:
        context: ./vue-frontend
        dockerfile: Dockerfile
    ports:
        - "10001:80"
    restart: 'always'
    logging:
      driver: "json-file"
      options:
        max-size: "10k"
        max-file: "3"